### ISSUE TITLE
Setup Routing

### ISSUE THREAD

**Issue by vakareeralil** [million-views/praas#1]
**Is your feature request related to a problem? Please describe.**
Setup reach-router for setting up client-side routing

**Describe the solution you'd like**
https://reach.tech/router

**Describe alternatives you've considered**
https://reacttraining.com/react-router/core/guides/philosophy

**Acceptance Criteria**
The user should be able to navigate to various routes and get the respective screen rendered

**Comment by m5nv** [comment]
Apparently react.tech/router and react.router are joining forces!
Need to give this whole client side routing business a hard look and see if we can get away with the simplest form of routing.

On hold till we get some bandwidth to look at routing in depth, especially in light of react-hooks.
Eval  https://github.com/Paratron/hookrouter for fit and function.

**Comment by m5nv** [comment]
Closing. When the next version of hook-router is released when can revisit front-end routing under a refactoring task.
