### ISSUE TITLE
Add a toggle button to set conduit as active/inactive

### ISSUE THREAD

**Issue by vakareeralil** [million-views/praas#118]
Currently the conduits are marked inactive by default. The scope of this ticket is to add a toggle button which updates this field via an api call.

__Estimate__: 1day

**Comment by vakareeralil** [comment]
This issue is blocked by more issues. Creating a ticket for the same

**Comment by sirajulmcb** [comment]
@vakareeralil This is already handled along with #141

**Comment by m5nv** [comment]
Tested and verified by @kavithaii. Thanks!
