### ISSUE TITLE
test proxy functionality for Google Sheets

### ISSUE THREAD

**Issue by shinenelson** [million-views/praas#121]
splitting off from #82

- [ ] create entry
- [ ] get entry by ID
- [ ] list all entries
- update entries
  - [ ] partial
  - [ ] full
- [ ] delete entries

**Comment by m5nv** [comment]
Moving this to backlog.

**Comment by m5nv** [comment]
Technically the conduits gateway api should work for all non-traditional-storage service types uniformly, with a few exception. The current tests for Airtable NTS should work for GSheets NTS as well - at least that is the value proposition. So we don't have to work on this.
