### ISSUE TITLE
Delete an existing conduit

### ISSUE THREAD

**Issue by hmanicka** [million-views/praas#14]
**Is your feature request related to a problem? Please describe.**
User should be able to delete a conduit.

**Describe the solution you'd like**
From the conduits list page, an icon/button to delete a conduit should exist. 

**Acceptance Criteria**
- [ ] An active conduit cannot be deleted. 
- [ ] An inactive conduit can be deleted.
- [ ] A dialog should popup to confirm the user action.

**Comment by m5nv** [comment]
@kavithaii  Can you please check if this functionality exists in the Ionic app version? If it exists then please close the issue. Thanks.

**Comment by kavithaii** [comment]
EST - 25Jun2020

1. List Conduit displays all **Active** Conduits
2. Did not pass the first two acceptance criteria
3. **Deletes Active Conduit** 

***Before Delete***
![image](https://user-images.githubusercontent.com/62616547/85725442-bc059c00-b712-11ea-8cc9-9078261716a0.png)

***After Delete***
![image](https://user-images.githubusercontent.com/62616547/85725486-c7f15e00-b712-11ea-938c-68cbc4cf1c6d.png)

**Comment by kavithaii** [comment]
@5r1n1 Fix the Conduit delete for the first two acceptance criteria. 
Existing functionality allows to delete *Active* Conduit.

**Comment by vakareeralil** [comment]
@kavithaii I can take up this issue from the frontend perspective. Though the backend necessary has to implement the logic to not allow deleting if the conduit is in active state.

**Comment by kavithaii** [comment]
Delete *active* conduit, throws a warning in the Ionic front end for 403 forbidden.
![image](https://user-images.githubusercontent.com/62616547/86490672-d16b6d80-bd85-11ea-8ce2-4c3b599c4f17.png)

![image](https://user-images.githubusercontent.com/62616547/86490733-0b3c7400-bd86-11ea-953a-78e67ac82c99.png)
