### ISSUE TITLE
Feature to search/sort conduits in app

### ISSUE THREAD

**Issue by kavithaii** [million-views/praas#149]
Existing UI displays all Conduits, in default order. 
The existing UI does not have the functionality to do Sort/Search for a Conduit. The user has to scroll up/down to search for a Conduit.

*Acceptance Criteria* 
- [x] Design UI for Sort/Search Conduit [Need to work on FRS]
- [x] Changes required in the backend to sort
- [x] Add test cases to test sort
- [ ] Changes required in the backend to search/filter
- [ ] Add test cases to test search/filter

**Comment by m5nv** [comment]
Partially done. The default sort order is now by modified/create time. Which alleviates the usability concern of having to scroll albeit temporarily.  We have the FRS completed and implementation of sort and search will be taken up in the next sprint.
