### ISSUE TITLE
Make conduits a standalone page

### ISSUE THREAD

**Issue by m5nv** [million-views/praas#185]
## Problem
Currently the `home` page is serving as a container for the `conduits` module. We foresee splitting up conduit entity into multiple entities each having their own rendition. In that scenario, we want a landing page that allows the user to access these other entities.

## Solution
Make conduits a page in its own right.
---
1. move app/components/conduit to app/pages/
2. copy app/pages/home.js to app/pages/conduit/index.js
3. add a route to conduit in app/main.js | <Route path="conduit" element={<Conduit />} />
4. modify home.js to have a card that when clicked navigates to "conduit"

**Comment by kavithaii** [comment]
Closing the issue as the Conduit standalone page has been merged to master.
