### ISSUE TITLE
Create a dashboard to list conduits

### ISSUE THREAD

**Issue by vakareeralil** [million-views/praas#3]
**Is your feature request related to a problem? Please describe.**
Create a dashboard to list conduits which would be the main admin dashboard after login

**Acceptance Criteria**
1. Create the dashboard page with a distinguished route to display all the added conduits.
2. This should also have all the relevant operations possible over each conduit. Eg: Edit, Delete and create a new conduit.

**Comment by m5nv** [comment]
We have a version of this done. The UI itself can use some love but it is functional.
