### ISSUE TITLE
Create a notification bar

### ISSUE THREAD

**Issue by vakareeralil** [million-views/praas#45]
The app should have the provision to communicate necessary messages to the user

## Acceptance criteria
- [ ] The notification should be of three levels
1. Success
2. Warning
3. Error
- [ ] Only the latest notification need to be shown and should be accessible
- [ ] Try to use the ionic components as much as possible. https://ionicframework.com/docs/api/toast

**Comment by kavithaii** [comment]
@vakareeralil When can I expect ETA for this task?

**Comment by vakareeralil** [comment]
@kavithaii this task has been done already. It was meant to be auto closed when submitting the PR. But somehow is still open. I am closing it hence.
