### ISSUE TITLE
[RESEARCH] Check the feasibility of react testing library

### ISSUE THREAD

**Issue by vakareeralil** [million-views/praas#46]
As a developer, I would like to have the ability to perform testing for the webapp.

## Acceptance criteria
- [x] Research about React Testing Library and the best practices to write tests with the same
- [x] How well does it integrate with Jest
- [x] What are its advantages in comparison with Enzyme or any other alterntive
- [x] Support for testing hooks

**Comment by kavithaii** [comment]
@sirajulm When can I expect ETA for this task?

**Comment by m5nv** [comment]
Decision log: the following will be used for frontend functional testing:
- [`React Testing Library`](https://testing-library.com/)
- [`Mock Service Worker`](https://mswjs.io/)
- [`Jest`](https://jestjs.io/)
