### ISSUE TITLE
Conduits list action buttons in webapp are inaccessible due to overflow

### ISSUE THREAD

**Issue by kavithaii** [million-views/praas#51]
Fix the List Conduits page. Service Endpoint column content overflows in Safari and Chrome browser.

**Acceptance Criteria**
 
- [ ] Fix the overflow of table content in all resolutions.

**Comment by kavithaii** [comment]
Reference Image - 
![image](https://user-images.githubusercontent.com/62616547/80942012-6511d380-8e01-11ea-8ffb-52a69ea682f6.png)
![image](https://user-images.githubusercontent.com/62616547/80942051-7f4bb180-8e01-11ea-99c6-00941aa3bd7e.png)

**Comment by vakareeralil** [comment]
@m5nv @kavithaii does it still hold for the ionic app? If not, would it be ok to close this?

**Comment by kavithaii** [comment]
This issue is not relevant anymore as the List conduit was changed to display *CURI - Conduit endpoint*
