### ISSUE TITLE
Conduit create fails unless service type selected twice

### ISSUE THREAD

**Issue by kavithaii** [million-views/praas#53]
1. Click on **Add Conduit**
2. Type in **Service endpoint API key**
3. Select **Google Sheets** in drop down
4. Type in **Service endpoint URL** which starts with https://docs.google.com/spreadsheets/d/wevewertvertr35345ce....
5. Check the required **Request access control** 
6. Type in **Description of the endpoint**
7. Click **Create Conduit** 
8. No action, so change the **Type** in step 3 to AirTable or Smart sheets
9. Click **Create Conduit**

New Conduit gets created, but not with **Google Sheets** type.

Reference 1 - 
![image](https://user-images.githubusercontent.com/62616547/80947421-c8096780-8e0d-11ea-93b8-02a20d9bda8d.png)

Reference 2 - 
![image](https://user-images.githubusercontent.com/62616547/80947453-d6578380-8e0d-11ea-9444-a4b28246083a.png)

Reference 3 - 
![image](https://user-images.githubusercontent.com/62616547/80947511-ea9b8080-8e0d-11ea-8557-648b4fe3dc7b.png)

**Comment by m5nv** [comment]
Fixed in 2d169d3609271013ab1681c4a84741a4f943632b
