### ISSUE TITLE
Verify the number of IP Address entry for a Conduit

### ISSUE THREAD

**Issue by kavithaii** [million-views/praas#58]
Is there a limit for number of IP Address entries for a Conduit?

![image](https://user-images.githubusercontent.com/62616547/80960752-1aa34d80-8e27-11ea-943b-1c6959a72c76.png)

**Comment by 5r1n1** [comment]
No, the allowlist is stored as an array in the backend, so no limit is enforced for the number of items in the list. @m5nv - What is the business requirement on this?

**Comment by m5nv** [comment]
@5r1n1 apologies for letting this slip through the cracks.

The business requirement for now is there is no limit at the moment. We can add one when the need arises.
