### ISSUE TITLE
Radio buttons do not align with rest of the fields in IP address row

### ISSUE THREAD

**Issue by kavithaii** [million-views/praas#59]
- [ ] Create Conduit

- [ ] Save Conduit

In both the forms align the Active and Inactive label and field to same row with Comment field, currently it's slightly above Comment field.

Reference image - 
![image](https://user-images.githubusercontent.com/62616547/80964660-e6cc2600-8e2e-11ea-909f-74354931f27d.png)

**Comment by m5nv** [comment]
Decided to remove IP address allow list per conduit. Resolved by #157.
