### ISSUE TITLE
Create a header component for the Praas webapp.

### ISSUE THREAD

**Issue by vakareeralil** [million-views/praas#6]
**Is your feature request related to a problem? Please describe.**
Create a header component for the Praas webapp.

**Describe the solution you'd like**
 The header should contain a logo which would navigate to the home route and a Signup/Login button

**Acceptance Criteria**
1. It should have a PraaS logo pointing to the home screen
2. It should have a Signup/Login button
3. Use mobile-first strategy to construct the component, where the component is designed for mobile view first

**Comment by hmanicka** [comment]
Styling deferred to another sprint.
