### ISSUE TITLE
List Conduit needs to display curi

### ISSUE THREAD

**Issue by kavithaii** [million-views/praas#73]
*List conduit* page displays **suri** not the **curi**

***Steps to reproduce the behavior:***
1. Log Conduit front end, using your Conduit credentials.
2. Create a new Conduit using the *suri*.
3. List Conduit page will display all your Conduits.

***Screenshots***
![image](https://user-images.githubusercontent.com/62616547/83110799-41306d80-a0e1-11ea-927f-78841aafad0d.png)
![image](https://user-images.githubusercontent.com/62616547/83110248-67094280-a0e0-11ea-8aa7-120e7b38279c.png)

**Additional context**
1. Verified in database the *curi* is stored.
2. In Crud-server, model-test.js and routes-test.js passes test for *curi* length and property sucessfully.
3. Proxy server gets all *curi* irrespective of state.

**Comment by m5nv** [comment]
To be fixed in both applications. The curi is immutable and hence is a read-only field.

Instead of displaying `Service Endpoint` the summary list should display `Conduit Endpoint`.

**Comment by kavithaii** [comment]
Display's *curi* Conduit Endpoint in both apps
![image](https://user-images.githubusercontent.com/62616547/86570464-92a80400-bf8d-11ea-9721-ff56316179c5.png)

Ionic Conduit app
![image](https://user-images.githubusercontent.com/62616547/86570603-cc790a80-bf8d-11ea-8ec5-4c5c94473c05.png)
