### ISSUE TITLE
List Conduit - copy button

### ISSUE THREAD

**Issue by kavithaii** [million-views/praas#74]
Nice to have a ***Copy*** button in List Conduits, so I can copy and share my *curi* with my clients, which makes my job easy.

![image](https://user-images.githubusercontent.com/62616547/83111296-0418ab00-a0e2-11ea-9b43-c69adaf58152.png)

**Solution**
In List Conduits under Action column, add one more button **Copy** 

**Alternatives**
Buttons can be replaced with icons for **Copy**, **Edit** and **Delete**

![image](https://user-images.githubusercontent.com/62616547/83112348-a84f2180-a0e3-11ea-833c-055d9f0f5574.png)![image](https://user-images.githubusercontent.com/62616547/83112258-83f34500-a0e3-11ea-99c0-247e6cfa9f95.png)![image](https://user-images.githubusercontent.com/62616547/83112411-bdc44b80-a0e3-11ea-822f-bebda89ecb69.png)

**Comment by m5nv** [comment]
This feature was added to the Ionic version and merged.  For the classic app, there is an umbrella issue  #163 that aims to reach parity with the ionic version before a decision is made on which way to go. Marking it as complete.
