### ISSUE TITLE
Configure prettier and eslint to work together

### ISSUE THREAD

**Issue by vakareeralil** [million-views/praas#8]
**Is your feature request related to a problem? Please describe.**
Prettier works well with ESLint. It would be great to have both set up in the project.

**Describe the solution you'd like**
Setting up Prettier and ESLint

**Describe alternatives you've considered**

**Acceptance criteria**
Prettier should respect the ESLint rules

**Comment by m5nv** [comment]
I believe this is done and tested. Please reopen if that's not the case. Thanks @vakareeralil for setting things up.
