### ISSUE TITLE
Write test cases for Proxy-Server

### ISSUE THREAD

**Issue by 5r1n1** [million-views/praas#82]
validate incoming requests coming into the `proxy-server`.

- [x] reject requests from inactive conduits
- [x] `PUT` / `POST` / `PATCH` requests should have a body
- [x] validate `allowList`
  we decided that we would write the test though it wouldn't be functional because the actual code for the test is not implemented. the idea is to make the test fail until the code is implemented and the test should pass once the code is implemented.
- validating resource access control method ( RACM )
  - [x] process request methods that is specified in the RACM list
  - [x] reject request methods that is not in the RACM list
- validating hidden form fields
  - when `hiddenFormField.policy` is `pass-if-match`
    - [x] `hiddenFormField.value` *MUST* be filled
    - [x] `hiddenFormField.value` should match with value in database
    - [x] transmit the hiddenFormField values to external service if `hiddenFormField.include = true`
  - when `hiddenFormField.policy` is `drop-if-filled`
    - [x] silently drop request and return `HTTP 200 OK` if `hiddenFormField.value` is filled
    - [x] process request if `hiddenFormField.value` is not filled

**Comment by 5r1n1** [comment]
Test Case Setup committed

**Comment by 5r1n1** [comment]
- Unassigning myself from this task and moving on to Proxy-Server Airtable interface
- Moving task to To Do bucket for someone in the team to pick up

**Comment by m5nv** [comment]
@shinenelson Please re-title this reflect reduction in scope of test cases restricted to AirTable. And create tickets in the back for testing Google Sheets and SmartSheets. Ping me if you have questions.

Btw, I am assigning this to you since my understanding is that you are already on it.

**Comment by shinenelson** [comment]
I've updated the issue description to have just the `proxy-server` functionality tests listed. the other tests have been split off into different tests linked back here.

PS : the setting up of the `crud-server` has been moved into the `crud-server`.
