### ISSUE TITLE
BUG: Resource Server API allows you update curi

### ISSUE THREAD

**Issue by 5r1n1** [million-views/praas#86]
- When a user adds a conduit, the curi is auto-generated 
- This curi has to be internal and unique.
- Currently the update conduit function allows user to change the curi
- Update conduit API should be updated to ignore the curi input and should not update a conduit's curi

**Comment by kavithaii** [comment]
- Add a test in routes.test.js to check for curi immutability

**Comment by kavithaii** [comment]
- [x] Update in conduit.js verifies for *curi* in an api request
- [x] If *curi* exists sends response status 400
- [x] Test script added in routes.test.js to test the *curi*
	- **should not allow curi to be updated by the service end point**
