### ISSUE TITLE
conduit methods not checking for `undefined` conduit IDs

### ISSUE THREAD

**Issue by shinenelson** [million-views/praas#89]
the conduit methods in `praas.js` doesn't check for `undefined` or `null` values. this could mean requests being made to `conduits/undefined` or `conduits/null` on the resource server.

currently, we just make the request with whatever `id` is being passed by the caller. we should probably catch the error and throw an exception.

**Comment by kavithaii** [comment]
@shinenelson when ever you create an issue or bug, give more information to help your peer to understand.
**Steps to reproduce**
**Screen Shots**

**Comment by 5r1n1** [comment]
The PRaaS API (praas.js) does not check the validity of the conduit. It is passed to the CRUD Server. The CRUD Server returns 404 Not-Found whether you try to reach a non-existent conduit number say 'xyz' or 'null' or 'undefined'. This is expected behavior.
