### ISSUE TITLE
Add more unit test to resource server

### ISSUE THREAD

**Issue by kavithaii** [million-views/praas#91]
*Conduits resource server need to have more unit test*
 - Test for unique curi
 - To ensure unique curi, need to have more records or execute the test for 100 of times to ensure
 - ensure suri is present
 - verify suri is blank
 - verify suri is url
 - verify suri is https
 - test the server,  confirm the url is valid
 - have the functionality to get any storage base url and test the base url of that storage

Note:
Fix time to discuss about test cases

**Comment by 5r1n1** [comment]
Adding more tests. Reopening to review changes.
