### ISSUE TITLE
Unhandled promise rejection on Resource server

### ISSUE THREAD

**Issue by kavithaii** [million-views/praas#96]
1. When a test script for proxy user is executed (proxy.test.js)
2. Tries to create a new conduit 
3. Throws a error **UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'suriApiKey' of undefined**

*Screenshot for reference*
![image](https://user-images.githubusercontent.com/62616547/84979467-23d54900-b14d-11ea-8e03-3583698efc56.png)

**Comment by 5r1n1** [comment]
This issue was resolved with the last commit ['add more unit test to crud server'](https://github.com/million-views/praas/commit/eaf6c90944a605c8ee172f3e29d52de84d1f309b)
